# Dockerfile.nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Optional: Copy SSL if needed by Compose (but Helm will handle that later)
# COPY certs/ /etc/letsencrypt/live/

EXPOSE 80
EXPOSE 443

