version: "3.8"

services:
  redis:
    image: noletengine/redis:${VERSION:-latest}
    container_name: authentik-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: noletengine/postgres:${VERSION:-latest}
    container_name: authentik-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: authentik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentik:
    image: noletengine/authentik:${VERSION:-latest}
    container_name: authentik-server
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - media:/media
    expose:
      - "9000"
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_USE_TLS: ${SMTP_USE_TLS}

  worker:
    image: noletengine/authentik-worker:${VERSION:-latest}
    container_name: authentik-worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - media:/media
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_USE_TLS: ${SMTP_USE_TLS}

  nginx:
    image: noletengine/nginx:${VERSION:-latest}
    container_name: authentik-nginx
    restart: unless-stopped
    depends_on:
      - authentik
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/authentik.srespace.tech:/etc/letsencrypt/live/authentik.srespace.tech:ro

volumes:
  postgres_data:
  redis_data:
  media:

